# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeting.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0egreeting.proto\"t\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"A\n\x0cGreetingType\x12\x0c\n\x08\x46RIENDLY\x10\x00\x12\n\n\x06\x46ORMAL\x10\x01\x12\n\n\x06\x43\x41SUAL\x10\x02\x12\x0b\n\x07HOSTILE\x10\x03\x62\x06proto3'
)



_GREETINGREQUEST_GREETINGTYPE = _descriptor.EnumDescriptor(
  name='GreetingType',
  full_name='GreetingRequest.GreetingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FRIENDLY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CASUAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOSTILE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=69,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_GREETINGREQUEST_GREETINGTYPE)


_GREETINGREQUEST = _descriptor.Descriptor(
  name='GreetingRequest',
  full_name='GreetingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GreetingRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='GreetingRequest.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GREETINGREQUEST_GREETINGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=134,
)

_GREETINGREQUEST_GREETINGTYPE.containing_type = _GREETINGREQUEST
DESCRIPTOR.message_types_by_name['GreetingRequest'] = _GREETINGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'greeting_pb2'
  # @@protoc_insertion_point(class_scope:GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)


# @@protoc_insertion_point(module_scope)
