# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("greeting.proto", :syntax => :proto3) do
    add_message "GreetingRequest" do
      optional :name, :string, 1
      optional :language, :string, 2
    end
    add_enum "GreetingRequest.GreetingType" do
      value :FRIENDLY, 0
      value :FORMAL, 1
      value :CASUAL, 2
      value :HOSTILE, 3
    end
  end
end

GreetingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GreetingRequest").msgclass
GreetingRequest::GreetingType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GreetingRequest.GreetingType").enummodule
